## Лекция 7
### Модуль NumPy

Лекция прочитана Иваном Кисляковым. Разрешено к использованию в некоммерческих образовательных целях. 

Текущее занятие во многом опирается на материал [лекций](https://miptstats.github.io/courses/python/05_numpy.html) miptStats

**Задание 1.**

Какие существую плюсы и минусы языка Python? С чем это связано?

**Задание 2.**

Узнайте, как и зачем можно замерять время работы программы?

Воспользуйтесь модулем [timeit](https://docs.python.org/3/library/timeit.html)



```python
import timeit
timeit.timeit("print('hi')", number=1)
```



In [7]:
import timeit

print(timeit.timeit("[i ** 0.5 for i in range(1, 10000000)]", number=1))

1.2984019999930752


In [13]:
print(timeit.timeit("list(map(lambda x: x ** 0.5, range(1, 10000000)))", number=1))

1.4234597499962547


In [83]:
# привет из будущего
print(timeit.timeit("__import__('numpy').arange(1, 10000000) ** 0.5", number=1))

0.274692375001905


In [14]:
print(timeit.timeit("map(lambda x: x ** 0.5, range(1, 10000000))", number=1))

3.625005774665624e-06


**Задание 3.**

Воспользуйтесь библиотекой **numpy**.

Что такое **массив**?

В чем категорическое различие со списками?

```python
import numpy as np
np.array(...)
```



In [15]:
import numpy as np


a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [16]:
a = np.array([1, 2, 3, "hello"])
print(a)

['1' '2' '3' 'hello']


In [18]:
a = np.array([1, 2, 3], dtype="int8")
print(a)
print(a.dtype)

[1 2 3]
int8


In [19]:
a = np.array([1, 2, 3])
print(a.dtype)

int64


**Задание 4.**

Воспользуйтесь атрибутом ``` array.dtype```

Попробуйте изменить тип данных элементов в массиве с помощью именнованного аргумента конструктора dtype.

**Задание 5.**

Воспользуйтесь функцией shape и reshape.

В чем различие с size()?

In [23]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
arr = np.array(lst)
print(arr.size)
print(arr.shape)


8
(8,)


In [29]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
arr = np.array(lst)
arr2 = arr.reshape(2, 4)
print(arr2)
arr2 = arr.reshape(4, 2)
print(arr2)
arr2 = arr.reshape(8, 1)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


**Задание 6.**

Попробуйте различную индексацию в двумерных массивах?

Работают ли срезки?

In [31]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
arr = np.array(lst)
arr = arr.reshape(2, 4)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [39]:
print(arr[0, 2])
print(arr[0, :])
print(arr[0, 1:])
print(arr[:, 2])
print(arr[:2, :2])

3
[1 2 3 4]
[2 3 4]
[3 7]
[[1 2]
 [5 6]]


**Задание 7.**

Существует различные способы заполнения массива данными по умолчанию. К примеру:

```python
np.ones(10)
np.zeros(10)
np.arange(10)
np.random.random(10)
np.random.randint(0, 10)
np.linspace(0, 10, 4)
np.fromstring("10_20_30", sep="_")
```
Воспользуйтесь последовательным (массовым) применением функций.


In [46]:
print(np.ones(10))
print(np.zeros(10))
print(np.arange(10))
print(np.random.random(10))
print(np.random.randint(0, 10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 1 2 3 4 5 6 7 8 9]
[0.58357726 0.05540702 0.08953047 0.84404367 0.78567607 0.4132918
 0.37090723 0.75004416 0.63519606 0.75817538]
4


In [52]:
print(np.linspace(0, 10, 5))

print(np.fromstring("10_20_30", sep="_"))


[ 0.   2.5  5.   7.5 10. ]
[10. 20. 30.]


**Задание 8.**

Примените различные математические операции к двум массивам.

Не забывайте про составные операторы присваивания.

In [54]:
arr1 = np.linspace(0, 90, 10)
arr2 = np.arange(10)

print(arr1, arr2)

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.] [0 1 2 3 4 5 6 7 8 9]


#### Одномерные массивы одинакового размера

In [59]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1[1:] / arr2[1:])

[ 0. 11. 22. 33. 44. 55. 66. 77. 88. 99.]
[ 0.  9. 18. 27. 36. 45. 54. 63. 72. 81.]
[  0.  10.  40.  90. 160. 250. 360. 490. 640. 810.]
[10. 10. 10. 10. 10. 10. 10. 10. 10.]


#### Одномерные массивы и число

In [61]:
print(arr1 * 2)
print(arr1 + 2)
print(arr1 - 2)
print(arr1 / 2)

[  0.  20.  40.  60.  80. 100. 120. 140. 160. 180.]
[ 2. 12. 22. 32. 42. 52. 62. 72. 82. 92.]
[-2.  8. 18. 28. 38. 48. 58. 68. 78. 88.]
[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45.]


#### Одномерные массивы разного размера

In [62]:
print(arr1 + arr2[5:])

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

#### Двумерные массивы и число

In [64]:
arr1 = np.linspace(0, 90, 10)
arr2 = np.arange(10)
arr1 = arr1.reshape(2, 5)
arr2 = arr2.reshape(2, 5)
print(arr1, arr2, sep="\n")

[[ 0. 10. 20. 30. 40.]
 [50. 60. 70. 80. 90.]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [66]:
print(arr1 * 2)
print(arr1 - 2)

[[  0.  20.  40.  60.  80.]
 [100. 120. 140. 160. 180.]]
[[-2.  8. 18. 28. 38.]
 [48. 58. 68. 78. 88.]]


#### Двумерные массивы и одномерный

In [69]:
arr3 = np.linspace(0, 10, 5)
print(arr3)

[ 0.   2.5  5.   7.5 10. ]


In [71]:
print(arr2 + arr3)
print(arr2.shape, arr3.shape)

[[ 0.   3.5  7.  10.5 14. ]
 [ 5.   8.5 12.  15.5 19. ]]
(2, 5) (5,)


In [72]:
arr3 = np.linspace(0, 10, 2)
print(arr2.shape, arr3.shape)

(2, 5) (2,)


In [75]:
print(arr2 + arr3)

ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

In [77]:
print((arr2.reshape(5, 2) + arr3).reshape(2, 5))

[[ 0. 11.  2. 13.  4.]
 [15.  6. 17.  8. 19.]]


**Задание 9.**

Примените различные знаки сравнения к двум массивам (или массив и число).

In [80]:
arr1 = np.linspace(0, 90, 10)
arr2 = np.arange(10)

print(arr1 <= arr2)
print(arr1 <= 55)



[ True False False False False False False False False False]
[ True  True  True  True  True  True False False False False]


**Задание 10.**

Поработайте с такими значениями, как:


```python
np.inf
np.nan
-np.inf
```
Что будет, если применить к ним арифметические операции?

Как вообще можно получить подобные значения?




In [95]:
print(-np.inf)
print(1/np.inf)
print(0 * np.inf)
print(np.inf - np.inf)
print(0 /np.inf)
print("ужас", np.sqrt(-1))
print((-1) ** 0.5)

-inf
0.0
nan
nan
0.0
ужас nan
(6.123233995736766e-17+1j)


/var/folders/4q/nkzzk4wn2ml3phylc260cbkr0000gp/T/ipykernel_19546/169935999.py:6: RuntimeWarning: invalid value encountered in sqrt
  print("ужас", np.sqrt(-1))


**Задание 11.**

Воспользуйтесь следующим кодом, посмотрите, что он делает?

Подумайте, как это можно использовать совместно с уже изученным материалом?

```python
filter = np.array([True, False, True])
array = np.array([1, 2, 3])
print(array[filter])
array[filter] = -1
print(array)
```



In [97]:
filter = np.array([True, False, True])
array = np.array([1, 2, 3])
print(array[filter])
array[filter] = -1
print(array)

[1 3]
[-1  2 -1]


In [99]:
array = np.array([1, 2, 3])
filter = np.array([1, 0, 2])
print(array[filter])

[2 1 3]


In [102]:
array = np.array([1, 2, 3])
filter = array > 1
array = array[filter]
print(array)



[2 3]


In [103]:
array = np.array([1, 2, 3])
print(array[array > 1])

[2 3]


**Задание 12.**

Посмотрите на функции ниже и поймите, что они делают?


```python
matrix.sum()
matrix.prod()
matrix.max()
matrix.min()
matrix.mean()
```



In [107]:
array = np.random.random(100) * 100
print(array)

[ 2.84138671 27.35863182 41.89994667 54.03498623 88.68531124 15.50052617
 92.52319065 84.80761913 12.38237071 46.04442817 20.02624089 83.70956877
 83.07484814 52.53281465  1.03986112 50.0861382  76.74193358 80.79231506
 49.42262197 20.16328196 83.98768797 12.47853488 63.90693842 53.11339058
 94.81124553 90.97030805 33.43868015 56.47879515 83.35604317 89.82850174
 34.48078172 29.19488223 79.02329806 12.70542056 51.35159616 62.4056278
 91.17619184 84.099454   77.31685838 48.11734431 63.69117292  8.69459166
 32.36895659 84.52875502  2.25479769  7.45021093 66.72699337 74.94888715
 18.20132582 37.12132789 50.95590777 64.74432403 63.56676845 88.05411268
  5.47364664 42.20774012 26.20994188 51.06993747 25.39735682 34.78268849
 81.92545299 94.76576171 19.38013045 96.54039157  8.29097766 80.8712125
 55.90522694 91.06120919 80.46780614  3.84133893 37.59931612 65.86439368
 23.35715369  4.43136887 22.73949045 37.70358595 15.43017739 64.39335426
 45.59736874 63.43398707 44.10220252 83.35501285 38.1

In [115]:
print(array.sum())
print(np.zeros(10).prod())
print(array.max())
print(array.min())
print(np.array([1, 2, 3, 4]).mean())

5138.393417663022
0.0
99.85892527629964
0.27514573353735194
2.5


**Задание 13.**

Посмотрите на функции ниже и поймите, что они делают?


```python
np.sqrt(number)
np.exp(number)
np.log(number)
np.sin(number)
np.cos(number)
np.e
np.pi
```

Попробуйте вписать matrix вместо number.

**Задание 14.**

Поработайте с матрицами, воспользуйтесь следующими методами:



```python
matrix.transpose()
np.rot90(matrix)
np.rot90(matrix, -1)
np.linalg.det(matrix)
np.dot(matrix1, matrix2) # или @
```

In [116]:
matrix = np.arange(0, 10).reshape(2, 5)
print(matrix)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [117]:
print(matrix.transpose())

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [120]:
print(np.rot90(matrix, -1))

[[5 0]
 [6 1]
 [7 2]
 [8 3]
 [9 4]]


In [124]:
print(np.linalg.det(np.random.random(25).reshape(5, 5)))

0.04383407807720529


In [126]:
matrix1 = np.arange(10).reshape(5, 2)
matrix2 = np.arange(5, 11).reshape(2, 3)

np.dot(matrix1, matrix2)

array([[  8,   9,  10],
       [ 34,  39,  44],
       [ 60,  69,  78],
       [ 86,  99, 112],
       [112, 129, 146]])

**Задание 15.**

Работа с массивами:



```python
np.hstack((matrix1, matrix2))
np.hsplit(matrix, [pos1, pos2, pos3])
np.delete(matrix, id)
np.insert(matrix, id, [-1, -1, -1])
np.append(matrix, matrix2)
```



**Задание 16.**

Создайте несколько двумерных матриц.

Например, создайте единичную матрицу (np.eye(rang)).

Воспользуйтесь методами поиска **вдоль оси**


```python
matrix.sum()
matrix.sum(axis=0)
matrix.sum(axis=1)

matrix.max()
matrix.max(axis=0)
matrix.max(axis=1)
```
Подумайте, какие еще методы можно использовать для подобных вещей?


In [127]:
matrix = np.arange(10).reshape(5, 2)
print(matrix)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [130]:
print(matrix.sum())
print(matrix.size)
print(matrix.shape)

45
10
(5, 2)


In [132]:
print(matrix.sum(axis=0))
print(matrix.sum(axis=1))

[20 25]
[ 1  5  9 13 17]


In [140]:
print((np.eye(4) * np.arange(1, 5)))

[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


In [138]:
print((np.eye(4) * np.arange(1, 5)).max(axis=0))

[1. 2. 3. 4.]


**Задание 17.**

Отсортируйте одномерный массив:

```python
np.sort(matrix)
```

А потом двумерный:

```python
np.sort(matrix)
np.sort(matrix, axis=0)
np.sort(matrix, axis=1)
np.sort(matrix, axis=None)
```


**Задание 18.**

Создайте массив arr из 20 случайных целых чисел от 0 до 100.

Найдите максимальное, минимальное и среднее значение в этом массиве.

Измените форму массива на (5, 4).

Отсортируйте каждую строку получившейся матрицы.


**Задание 19.**

Создайте две матрицы A (3x3) и B (3x3) со случайными значениями от 1 до 10.

Вычислите:

Произведение матриц (A @ B).

Поэлементное умножение (A * B).

Определитель матрицы A.

Решите систему линейных уравнений:

A · X = C, где C = [5, 10, 15].

**Задание 20.**

Создайте массив data из 100 случайных чисел в диапазоне [-10, 10].

Замените все отрицательные числа в data на 0.

Найдите индексы элементов, которые больше 5.

Используя булеву маску, выберите только чётные числа из data.

**Задание 21.**

Создайте массив из 30 случайных чисел от 0 до 100.

Оставьте только числа, которые:

Больше 50.

Делится на 3 без остатка.